title: My Blog
description: "A space for my random thoughts and musings"
author:
  name: "Nick Jenkins"
  email: "NJenkins79@comcast.net"
  url: "https://www.linkedin.com/in/nicholas-jenkins-546000163/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
  - scope: 
      path: "assets/"
    values: 
      image: true

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Nick Jenkins"
year : "2019"
